Refactor theming
forus-labs/forui pull request #19
Opened 2024-05-21 12:08 UTC by Pante

This PR refactors theming.

Changes to scaling textstyles inside widget styles and an extension on BuildContext to provide a `font` getter will be introduce in a subsequent PR.

2024-05-21 16:32 UTC, kawaijoe requested changes

2024-05-21 16:32 UTC, kawaijoe commented on forui/lib/src/theme/themes.dart
> +        borderRadius: BorderRadius.circular(8),
Should we just add a default value for `borderRadius` on `FStyle` so we don't need to keep repeating it.

2024-05-21 16:32 UTC, kawaijoe commented on forui/lib/src/theme/themes.dart
> +import 'package:flutter/material.dart';
Just curious, are we avoiding importing `material`?

2024-05-21 16:32 UTC, kawaijoe commented on forui_assets/LICENSE
> +Copyright (c) 2024 Forus Labs
```suggestion
Copyright (c) 2024 Forus Labs Pte Ltd
```

2024-05-21 16:32 UTC, kawaijoe commented on LICENSE
> +Copyright (c) 2024 Forus Labs
```suggestion
Copyright (c) 2024 Forus Labs Pte Ltd
```

2024-05-21 16:32 UTC, kawaijoe commented on forui/docs/LICENSE
I don't think docs should exist inside `forui`. There should be documentation for everything in this repository.

2024-05-21 16:32 UTC, kawaijoe commented on forui/LICENSE
Might need to update the org name here as well

2024-05-22 01:45 UTC, Pante commented on forui/docs/LICENSE
I think I moved it by accident.

2024-05-22 05:48 UTC, merged