Add line calendar
forus-labs/forui pull request #296
Opened 2024-11-28 13:28 UTC by Pante

**Describe the changes**
This PR adds dynamic line calendar sizing based on the tiles' height. Resolves #295.

~~It does not fully support localization due to a really bad merge conflict with #282. It will be addressed in a follow-up PR once both PRs are merged.~~

**Checklist**
- [x] I have read the [CONTRIBUTING.md](../CONTRIBUTING.md).
- [x] I have included the relevant unit/golden tests.
- [x] I have included the relevant samples.
- [x] I have updated the documentation accordingly.
- [x] I have updated the [CHANGELOG.md](../forui/CHANGELOG.md) if necessary.

2024-12-06 14:47 UTC, kawaijoe commented
https://github.com/user-attachments/assets/5275ddbc-63fb-464e-92fb-6493c020e3e7

While not a bug with the sheet per se, I think it could be nice if we only allowed one sheet to show at a time.

2024-12-08 09:00 UTC, Daviiddoo requested changes

2024-12-08 09:07 UTC, Pante commented on forui/lib/src/widgets/line_calendar/speculative_layout.dart
> +class CalendarLayout extends StatefulWidget {
good point

2024-12-11 12:35 UTC, kawaijoe commented on samples/lib/widgets/line_calendar.dart
> +        controller: FCalendarController.date(initialSelection: DateTime.now().subtract(const Duration(days: 1))),
Do we need to dispose the controller?

2024-12-11 13:21 UTC, kawaijoe approved these changes

2024-12-11 13:39 UTC, merged